WIP: Pricequotation tender
ProzorroUKR/openprocurement.api pull request #39
Opened 2020-05-07 11:58 UTC by yshalenyk

## Процедура PriceQuotation(Запит цінових пропозицій)

### Workflow
1. Створення процедури у статусі `draft`
2. Переведення процедури в статус `draft.publishing`
3. Наповнення процедури додатковою інформацією за допомогою робота `priceQuotationBot`
4. Переведення роботом процедури в статус `active.tendering`(або відхилення процедури в статус `unsuccessful`)
5. Подача пропозицій
6. Після завершення `tenderPeriod` процедура переходить у статус `active.qualification`(або статус `unsuccessful`, якщо пропозицій не надійшло)
7. Після вибору переможця процедура переходить в статус `active.awarded`
8. Після підписання контракту процедура переходить в статус `complete`

### Зміни в систему доступів
Для можливості роботом змінювати і доповнювати процедуру додано права на зміну тендера ботом

https://github.com/openprocurement/ProzorroUKR-openprocurement.api/blob/bb31178496000c19b032b0b79b5961ee68f747a6/src/openprocurement/tender/core/traversal.py#L27

### Подача пропозицій
При подачі bid-a учаснику необхідно вказувати ідентифікатор свого товару, зареєстрованого як позицію(`requirementsResponse`) в каталозі.

### TODO
- інтеграція з планами

2020-05-29 15:58 UTC, SergioAnd95 commented on docker-compose.yml
> +    ports:
Нужно убрать, так как это дублирование

2020-05-29 15:58 UTC, SergioAnd95 commented on src/openprocurement/tender/pricequotation/subscribers.py
> +    """ initialization handler for belowThreshold tenders """
Наверное описание стоит поправить)

2020-05-29 15:58 UTC, SergioAnd95 commented on src/openprocurement/tender/pricequotation/tests/cancellation.py
> +# class TenderCancellationActiveQualificationResourceTest(
Это наверное стоит убрать)

2020-05-29 15:58 UTC, SergioAnd95 commented on src/openprocurement/tender/pricequotation/tests/cancellation.py
> +    create_tender_cancellation_invalid,
Наверное тесты не стоило копировать, а просто импортнуть уже готовые. К тому же там есть миксины. Это касается всех тестов)

2020-05-29 15:58 UTC, SergioAnd95 commented on src/openprocurement/tender/pricequotation/tests/cancellation_blanks.py
> +@mock.patch("openprocurement.tender.core.models.RELEASE_2020_04_19", get_now() + timedelta(days=1))
К тому же в этих тестах роки RELEASE_2020_04_19, та как оно всё и так уже будет работать после данного релиза)

2020-05-29 15:58 UTC, SergioAnd95 commented on src/openprocurement/tender/pricequotation/models/cancellation.py
> +                "status",
У нас cancellation имеет начальный статус draft. По этому отсюда нужно убрать поле `status`

2020-05-29 15:58 UTC, SergioAnd95 commented on src/openprocurement/tender/pricequotation/models/cancellation.py
> +        choices=["draft", "pending", "unsuccessful", "active"],
Поскольку в PQ нету complaints для cancellation, то статус `pending` здесь не нужен. Можно глянуть как это реализовано в процедурах без complaint(например в belowThreshold). Пользователь должен переводить сразу из draft в active или unsuccessful.

2020-05-29 15:58 UTC, SergioAnd95 commented on src/openprocurement/tender/pricequotation/utils.py
> +def cancel_tender(request):
Эта функция по идее так же не нужна. так как статуса `pending` быть не должно.

2020-05-29 15:58 UTC, SergioAnd95 commented on src/openprocurement/tender/pricequotation/views/cancellation.py
> +        if cancellation.status == "active":
Это так же можно убрать.

2020-05-29 15:58 UTC, SergioAnd95 commented on src/openprocurement/tender/pricequotation/views/cancellation.py
> +        validators=(
Так же сюда нужно добавить валидацию по переходу статусов, взять её отсюда: https://github.com/ProzorroUKR/openprocurement.api/blob/aa626e5285b70b5afe8f838784cabacde795e8f7/src/openprocurement/tender/core/validation.py#L473

2020-06-09 20:37 UTC, yshalenyk commented on src/openprocurement/tender/pricequotation/tests/cancellation.py
> +    create_tender_cancellation_invalid,
Тести трохи порефакторив, але багато не вдалось перевикористати через різницю в процесах

2020-06-11 10:08 UTC, SergioAnd95 commented on docs/source/locale/uk/LC_MESSAGES/tendering/pricequotation/overview.po
> +msgstr ""
Здесь нужно добавить перевод

2020-06-11 10:34 UTC, SergioAnd95 commented on src/openprocurement/tender/pricequotation/tests/cancellation.py
> +    create_tender_cancellation_invalid,
ok)

2020-07-01 09:51 UTC, SergioAnd95 requested changes

2020-07-01 09:51 UTC, SergioAnd95 commented on src/openprocurement/tender/pricequotation/views/tender.py
> +                if data["tenderPeriod"]["endDate"] < calculated_end_date.isoformat():
 Почему валидацию по проверке tenderPeriod не вынести в модель ? как это происходит во всех тендерах.

2020-07-01 09:51 UTC, SergioAnd95 commented on src/openprocurement/tender/pricequotation/views/tender.py
> +                else:
Ну и else здесь можно убрать

2020-07-01 09:51 UTC, SergioAnd95 commented on src/openprocurement/tender/pricequotation/models/tender.py
> +        return True
Ну и здесь True можно и не возвращать) просто как единый стиль раз нигде больше не возвращается)

2020-07-22 07:29 UTC, closed without merging